/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FolderComponentRouteImport } from './routes/folder-component'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ApiSourceRouteImport } from './routes/api.source'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsDocsRouteRouteImport } from './routes/components/_docs/route'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as SponsorsThankYouRouteImport } from './routes/sponsors/thank-you'
import { Route as ComponentsDocsSlugRouteImport } from './routes/components/_docs/$slug'
import { Route as ComponentsDocsAnimatedCounterRouteImport } from './routes/components/_docs/animated-counter'
import { Route as ComponentsDocsBounceSidebarRouteImport } from './routes/components/_docs/bounce-sidebar'
import { Route as ComponentsDocsCodeBlockRouteImport } from './routes/components/_docs/code-block'
import { Route as ComponentsDocsDeleteButtonRouteImport } from './routes/components/_docs/delete-button'
import { Route as ComponentsDocsDurationPickerRouteImport } from './routes/components/_docs/duration-picker'
import { Route as ComponentsDocsEmojiReactionRouteImport } from './routes/components/_docs/emoji-reaction'
import { Route as ComponentsDocsFamilyDrawerRouteImport } from './routes/components/_docs/family-drawer'
import { Route as ComponentsDocsFluidOrbRouteImport } from './routes/components/_docs/fluid-orb'
import { Route as ComponentsDocsFolderComponentRouteImport } from './routes/components/_docs/folder-component'
import { Route as ComponentsDocsGithubActivityRouteImport } from './routes/components/_docs/github-activity'
import { Route as ComponentsDocsGooeyNavRouteImport } from './routes/components/_docs/gooey-nav'
import { Route as ComponentsDocsGravityLettersRouteImport } from './routes/components/_docs/gravity-letters'
import { Route as ComponentsDocsGridRevealRouteImport } from './routes/components/_docs/grid-reveal'
import { Route as ComponentsDocsHookSidebarRouteImport } from './routes/components/_docs/hook-sidebar'
import { Route as ComponentsDocsMatrixOrbRouteImport } from './routes/components/_docs/matrix-orb'
import { Route as ComponentsDocsNotificationBellRouteImport } from './routes/components/_docs/notification-bell'
import { Route as ComponentsDocsOtpInputRouteImport } from './routes/components/_docs/otp-input'
import { Route as ComponentsDocsProximitySidebarRouteImport } from './routes/components/_docs/proximity-sidebar'
import { Route as ComponentsDocsScrollProgressRouteImport } from './routes/components/_docs/scroll-progress'
import { Route as ComponentsDocsStepPlayerRouteImport } from './routes/components/_docs/step-player'
import { Route as ComponentsDocsTaskListRouteImport } from './routes/components/_docs/task-list'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderComponentRoute = FolderComponentRouteImport.update({
  id: '/folder-component',
  path: '/folder-component',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDocsRouteRoute = ComponentsDocsRouteRouteImport.update({
  id: '/components/_docs',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsThankYouRoute = SponsorsThankYouRouteImport.update({
  id: '/sponsors/thank-you',
  path: '/sponsors/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDocsSlugRoute = ComponentsDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsAnimatedCounterRoute =
  ComponentsDocsAnimatedCounterRouteImport.update({
    id: '/animated-counter',
    path: '/animated-counter',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsBounceSidebarRoute =
  ComponentsDocsBounceSidebarRouteImport.update({
    id: '/bounce-sidebar',
    path: '/bounce-sidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsCodeBlockRoute = ComponentsDocsCodeBlockRouteImport.update({
  id: '/code-block',
  path: '/code-block',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsDeleteButtonRoute =
  ComponentsDocsDeleteButtonRouteImport.update({
    id: '/delete-button',
    path: '/delete-button',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsDurationPickerRoute =
  ComponentsDocsDurationPickerRouteImport.update({
    id: '/duration-picker',
    path: '/duration-picker',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsEmojiReactionRoute =
  ComponentsDocsEmojiReactionRouteImport.update({
    id: '/emoji-reaction',
    path: '/emoji-reaction',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsFamilyDrawerRoute =
  ComponentsDocsFamilyDrawerRouteImport.update({
    id: '/family-drawer',
    path: '/family-drawer',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsFluidOrbRoute = ComponentsDocsFluidOrbRouteImport.update({
  id: '/fluid-orb',
  path: '/fluid-orb',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsFolderComponentRoute =
  ComponentsDocsFolderComponentRouteImport.update({
    id: '/folder-component',
    path: '/folder-component',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGithubActivityRoute =
  ComponentsDocsGithubActivityRouteImport.update({
    id: '/github-activity',
    path: '/github-activity',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGooeyNavRoute = ComponentsDocsGooeyNavRouteImport.update({
  id: '/gooey-nav',
  path: '/gooey-nav',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsGravityLettersRoute =
  ComponentsDocsGravityLettersRouteImport.update({
    id: '/gravity-letters',
    path: '/gravity-letters',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGridRevealRoute =
  ComponentsDocsGridRevealRouteImport.update({
    id: '/grid-reveal',
    path: '/grid-reveal',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsHookSidebarRoute =
  ComponentsDocsHookSidebarRouteImport.update({
    id: '/hook-sidebar',
    path: '/hook-sidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsMatrixOrbRoute = ComponentsDocsMatrixOrbRouteImport.update({
  id: '/matrix-orb',
  path: '/matrix-orb',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsNotificationBellRoute =
  ComponentsDocsNotificationBellRouteImport.update({
    id: '/notification-bell',
    path: '/notification-bell',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsOtpInputRoute = ComponentsDocsOtpInputRouteImport.update({
  id: '/otp-input',
  path: '/otp-input',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsProximitySidebarRoute =
  ComponentsDocsProximitySidebarRouteImport.update({
    id: '/proximity-sidebar',
    path: '/proximity-sidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsScrollProgressRoute =
  ComponentsDocsScrollProgressRouteImport.update({
    id: '/scroll-progress',
    path: '/scroll-progress',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsStepPlayerRoute =
  ComponentsDocsStepPlayerRouteImport.update({
    id: '/step-player',
    path: '/step-player',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsTaskListRoute = ComponentsDocsTaskListRouteImport.update({
  id: '/task-list',
  path: '/task-list',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components': typeof ComponentsDocsRouteRouteWithChildren
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/components/': typeof ComponentsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/components/$slug': typeof ComponentsDocsSlugRoute
  '/components/animated-counter': typeof ComponentsDocsAnimatedCounterRoute
  '/components/bounce-sidebar': typeof ComponentsDocsBounceSidebarRoute
  '/components/code-block': typeof ComponentsDocsCodeBlockRoute
  '/components/delete-button': typeof ComponentsDocsDeleteButtonRoute
  '/components/duration-picker': typeof ComponentsDocsDurationPickerRoute
  '/components/emoji-reaction': typeof ComponentsDocsEmojiReactionRoute
  '/components/family-drawer': typeof ComponentsDocsFamilyDrawerRoute
  '/components/fluid-orb': typeof ComponentsDocsFluidOrbRoute
  '/components/folder-component': typeof ComponentsDocsFolderComponentRoute
  '/components/github-activity': typeof ComponentsDocsGithubActivityRoute
  '/components/gooey-nav': typeof ComponentsDocsGooeyNavRoute
  '/components/gravity-letters': typeof ComponentsDocsGravityLettersRoute
  '/components/grid-reveal': typeof ComponentsDocsGridRevealRoute
  '/components/hook-sidebar': typeof ComponentsDocsHookSidebarRoute
  '/components/matrix-orb': typeof ComponentsDocsMatrixOrbRoute
  '/components/notification-bell': typeof ComponentsDocsNotificationBellRoute
  '/components/otp-input': typeof ComponentsDocsOtpInputRoute
  '/components/proximity-sidebar': typeof ComponentsDocsProximitySidebarRoute
  '/components/scroll-progress': typeof ComponentsDocsScrollProgressRoute
  '/components/step-player': typeof ComponentsDocsStepPlayerRoute
  '/components/task-list': typeof ComponentsDocsTaskListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components': typeof ComponentsIndexRoute
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/components/$slug': typeof ComponentsDocsSlugRoute
  '/components/animated-counter': typeof ComponentsDocsAnimatedCounterRoute
  '/components/bounce-sidebar': typeof ComponentsDocsBounceSidebarRoute
  '/components/code-block': typeof ComponentsDocsCodeBlockRoute
  '/components/delete-button': typeof ComponentsDocsDeleteButtonRoute
  '/components/duration-picker': typeof ComponentsDocsDurationPickerRoute
  '/components/emoji-reaction': typeof ComponentsDocsEmojiReactionRoute
  '/components/family-drawer': typeof ComponentsDocsFamilyDrawerRoute
  '/components/fluid-orb': typeof ComponentsDocsFluidOrbRoute
  '/components/folder-component': typeof ComponentsDocsFolderComponentRoute
  '/components/github-activity': typeof ComponentsDocsGithubActivityRoute
  '/components/gooey-nav': typeof ComponentsDocsGooeyNavRoute
  '/components/gravity-letters': typeof ComponentsDocsGravityLettersRoute
  '/components/grid-reveal': typeof ComponentsDocsGridRevealRoute
  '/components/hook-sidebar': typeof ComponentsDocsHookSidebarRoute
  '/components/matrix-orb': typeof ComponentsDocsMatrixOrbRoute
  '/components/notification-bell': typeof ComponentsDocsNotificationBellRoute
  '/components/otp-input': typeof ComponentsDocsOtpInputRoute
  '/components/proximity-sidebar': typeof ComponentsDocsProximitySidebarRoute
  '/components/scroll-progress': typeof ComponentsDocsScrollProgressRoute
  '/components/step-player': typeof ComponentsDocsStepPlayerRoute
  '/components/task-list': typeof ComponentsDocsTaskListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components/_docs': typeof ComponentsDocsRouteRouteWithChildren
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/components/': typeof ComponentsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/components/_docs/$slug': typeof ComponentsDocsSlugRoute
  '/components/_docs/animated-counter': typeof ComponentsDocsAnimatedCounterRoute
  '/components/_docs/bounce-sidebar': typeof ComponentsDocsBounceSidebarRoute
  '/components/_docs/code-block': typeof ComponentsDocsCodeBlockRoute
  '/components/_docs/delete-button': typeof ComponentsDocsDeleteButtonRoute
  '/components/_docs/duration-picker': typeof ComponentsDocsDurationPickerRoute
  '/components/_docs/emoji-reaction': typeof ComponentsDocsEmojiReactionRoute
  '/components/_docs/family-drawer': typeof ComponentsDocsFamilyDrawerRoute
  '/components/_docs/fluid-orb': typeof ComponentsDocsFluidOrbRoute
  '/components/_docs/folder-component': typeof ComponentsDocsFolderComponentRoute
  '/components/_docs/github-activity': typeof ComponentsDocsGithubActivityRoute
  '/components/_docs/gooey-nav': typeof ComponentsDocsGooeyNavRoute
  '/components/_docs/gravity-letters': typeof ComponentsDocsGravityLettersRoute
  '/components/_docs/grid-reveal': typeof ComponentsDocsGridRevealRoute
  '/components/_docs/hook-sidebar': typeof ComponentsDocsHookSidebarRoute
  '/components/_docs/matrix-orb': typeof ComponentsDocsMatrixOrbRoute
  '/components/_docs/notification-bell': typeof ComponentsDocsNotificationBellRoute
  '/components/_docs/otp-input': typeof ComponentsDocsOtpInputRoute
  '/components/_docs/proximity-sidebar': typeof ComponentsDocsProximitySidebarRoute
  '/components/_docs/scroll-progress': typeof ComponentsDocsScrollProgressRoute
  '/components/_docs/step-player': typeof ComponentsDocsStepPlayerRoute
  '/components/_docs/task-list': typeof ComponentsDocsTaskListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/components/'
    | '/sponsors/'
    | '/components/$slug'
    | '/components/animated-counter'
    | '/components/bounce-sidebar'
    | '/components/code-block'
    | '/components/delete-button'
    | '/components/duration-picker'
    | '/components/emoji-reaction'
    | '/components/family-drawer'
    | '/components/fluid-orb'
    | '/components/folder-component'
    | '/components/github-activity'
    | '/components/gooey-nav'
    | '/components/gravity-letters'
    | '/components/grid-reveal'
    | '/components/hook-sidebar'
    | '/components/matrix-orb'
    | '/components/notification-bell'
    | '/components/otp-input'
    | '/components/proximity-sidebar'
    | '/components/scroll-progress'
    | '/components/step-player'
    | '/components/task-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/sponsors'
    | '/components/$slug'
    | '/components/animated-counter'
    | '/components/bounce-sidebar'
    | '/components/code-block'
    | '/components/delete-button'
    | '/components/duration-picker'
    | '/components/emoji-reaction'
    | '/components/family-drawer'
    | '/components/fluid-orb'
    | '/components/folder-component'
    | '/components/github-activity'
    | '/components/gooey-nav'
    | '/components/gravity-letters'
    | '/components/grid-reveal'
    | '/components/hook-sidebar'
    | '/components/matrix-orb'
    | '/components/notification-bell'
    | '/components/otp-input'
    | '/components/proximity-sidebar'
    | '/components/scroll-progress'
    | '/components/step-player'
    | '/components/task-list'
  id:
    | '__root__'
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components/_docs'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/components/'
    | '/sponsors/'
    | '/components/_docs/$slug'
    | '/components/_docs/animated-counter'
    | '/components/_docs/bounce-sidebar'
    | '/components/_docs/code-block'
    | '/components/_docs/delete-button'
    | '/components/_docs/duration-picker'
    | '/components/_docs/emoji-reaction'
    | '/components/_docs/family-drawer'
    | '/components/_docs/fluid-orb'
    | '/components/_docs/folder-component'
    | '/components/_docs/github-activity'
    | '/components/_docs/gooey-nav'
    | '/components/_docs/gravity-letters'
    | '/components/_docs/grid-reveal'
    | '/components/_docs/hook-sidebar'
    | '/components/_docs/matrix-orb'
    | '/components/_docs/notification-bell'
    | '/components/_docs/otp-input'
    | '/components/_docs/proximity-sidebar'
    | '/components/_docs/scroll-progress'
    | '/components/_docs/step-player'
    | '/components/_docs/task-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderComponentRoute: typeof FolderComponentRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ComponentsDocsRouteRoute: typeof ComponentsDocsRouteRouteWithChildren
  ApiSourceRoute: typeof ApiSourceRoute
  SponsorsThankYouRoute: typeof SponsorsThankYouRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder-component': {
      id: '/folder-component'
      path: '/folder-component'
      fullPath: '/folder-component'
      preLoaderRoute: typeof FolderComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/_docs': {
      id: '/components/_docs'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsDocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/thank-you': {
      id: '/sponsors/thank-you'
      path: '/sponsors/thank-you'
      fullPath: '/sponsors/thank-you'
      preLoaderRoute: typeof SponsorsThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/_docs/$slug': {
      id: '/components/_docs/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsDocsSlugRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/animated-counter': {
      id: '/components/_docs/animated-counter'
      path: '/animated-counter'
      fullPath: '/components/animated-counter'
      preLoaderRoute: typeof ComponentsDocsAnimatedCounterRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/bounce-sidebar': {
      id: '/components/_docs/bounce-sidebar'
      path: '/bounce-sidebar'
      fullPath: '/components/bounce-sidebar'
      preLoaderRoute: typeof ComponentsDocsBounceSidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/code-block': {
      id: '/components/_docs/code-block'
      path: '/code-block'
      fullPath: '/components/code-block'
      preLoaderRoute: typeof ComponentsDocsCodeBlockRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/delete-button': {
      id: '/components/_docs/delete-button'
      path: '/delete-button'
      fullPath: '/components/delete-button'
      preLoaderRoute: typeof ComponentsDocsDeleteButtonRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/duration-picker': {
      id: '/components/_docs/duration-picker'
      path: '/duration-picker'
      fullPath: '/components/duration-picker'
      preLoaderRoute: typeof ComponentsDocsDurationPickerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/emoji-reaction': {
      id: '/components/_docs/emoji-reaction'
      path: '/emoji-reaction'
      fullPath: '/components/emoji-reaction'
      preLoaderRoute: typeof ComponentsDocsEmojiReactionRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/family-drawer': {
      id: '/components/_docs/family-drawer'
      path: '/family-drawer'
      fullPath: '/components/family-drawer'
      preLoaderRoute: typeof ComponentsDocsFamilyDrawerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/fluid-orb': {
      id: '/components/_docs/fluid-orb'
      path: '/fluid-orb'
      fullPath: '/components/fluid-orb'
      preLoaderRoute: typeof ComponentsDocsFluidOrbRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/folder-component': {
      id: '/components/_docs/folder-component'
      path: '/folder-component'
      fullPath: '/components/folder-component'
      preLoaderRoute: typeof ComponentsDocsFolderComponentRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/github-activity': {
      id: '/components/_docs/github-activity'
      path: '/github-activity'
      fullPath: '/components/github-activity'
      preLoaderRoute: typeof ComponentsDocsGithubActivityRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/gooey-nav': {
      id: '/components/_docs/gooey-nav'
      path: '/gooey-nav'
      fullPath: '/components/gooey-nav'
      preLoaderRoute: typeof ComponentsDocsGooeyNavRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/gravity-letters': {
      id: '/components/_docs/gravity-letters'
      path: '/gravity-letters'
      fullPath: '/components/gravity-letters'
      preLoaderRoute: typeof ComponentsDocsGravityLettersRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/grid-reveal': {
      id: '/components/_docs/grid-reveal'
      path: '/grid-reveal'
      fullPath: '/components/grid-reveal'
      preLoaderRoute: typeof ComponentsDocsGridRevealRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/hook-sidebar': {
      id: '/components/_docs/hook-sidebar'
      path: '/hook-sidebar'
      fullPath: '/components/hook-sidebar'
      preLoaderRoute: typeof ComponentsDocsHookSidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/matrix-orb': {
      id: '/components/_docs/matrix-orb'
      path: '/matrix-orb'
      fullPath: '/components/matrix-orb'
      preLoaderRoute: typeof ComponentsDocsMatrixOrbRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/notification-bell': {
      id: '/components/_docs/notification-bell'
      path: '/notification-bell'
      fullPath: '/components/notification-bell'
      preLoaderRoute: typeof ComponentsDocsNotificationBellRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/otp-input': {
      id: '/components/_docs/otp-input'
      path: '/otp-input'
      fullPath: '/components/otp-input'
      preLoaderRoute: typeof ComponentsDocsOtpInputRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/proximity-sidebar': {
      id: '/components/_docs/proximity-sidebar'
      path: '/proximity-sidebar'
      fullPath: '/components/proximity-sidebar'
      preLoaderRoute: typeof ComponentsDocsProximitySidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/scroll-progress': {
      id: '/components/_docs/scroll-progress'
      path: '/scroll-progress'
      fullPath: '/components/scroll-progress'
      preLoaderRoute: typeof ComponentsDocsScrollProgressRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/step-player': {
      id: '/components/_docs/step-player'
      path: '/step-player'
      fullPath: '/components/step-player'
      preLoaderRoute: typeof ComponentsDocsStepPlayerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/task-list': {
      id: '/components/_docs/task-list'
      path: '/task-list'
      fullPath: '/components/task-list'
      preLoaderRoute: typeof ComponentsDocsTaskListRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
  }
}

interface ComponentsDocsRouteRouteChildren {
  ComponentsDocsSlugRoute: typeof ComponentsDocsSlugRoute
  ComponentsDocsAnimatedCounterRoute: typeof ComponentsDocsAnimatedCounterRoute
  ComponentsDocsBounceSidebarRoute: typeof ComponentsDocsBounceSidebarRoute
  ComponentsDocsCodeBlockRoute: typeof ComponentsDocsCodeBlockRoute
  ComponentsDocsDeleteButtonRoute: typeof ComponentsDocsDeleteButtonRoute
  ComponentsDocsDurationPickerRoute: typeof ComponentsDocsDurationPickerRoute
  ComponentsDocsEmojiReactionRoute: typeof ComponentsDocsEmojiReactionRoute
  ComponentsDocsFamilyDrawerRoute: typeof ComponentsDocsFamilyDrawerRoute
  ComponentsDocsFluidOrbRoute: typeof ComponentsDocsFluidOrbRoute
  ComponentsDocsFolderComponentRoute: typeof ComponentsDocsFolderComponentRoute
  ComponentsDocsGithubActivityRoute: typeof ComponentsDocsGithubActivityRoute
  ComponentsDocsGooeyNavRoute: typeof ComponentsDocsGooeyNavRoute
  ComponentsDocsGravityLettersRoute: typeof ComponentsDocsGravityLettersRoute
  ComponentsDocsGridRevealRoute: typeof ComponentsDocsGridRevealRoute
  ComponentsDocsHookSidebarRoute: typeof ComponentsDocsHookSidebarRoute
  ComponentsDocsMatrixOrbRoute: typeof ComponentsDocsMatrixOrbRoute
  ComponentsDocsNotificationBellRoute: typeof ComponentsDocsNotificationBellRoute
  ComponentsDocsOtpInputRoute: typeof ComponentsDocsOtpInputRoute
  ComponentsDocsProximitySidebarRoute: typeof ComponentsDocsProximitySidebarRoute
  ComponentsDocsScrollProgressRoute: typeof ComponentsDocsScrollProgressRoute
  ComponentsDocsStepPlayerRoute: typeof ComponentsDocsStepPlayerRoute
  ComponentsDocsTaskListRoute: typeof ComponentsDocsTaskListRoute
}

const ComponentsDocsRouteRouteChildren: ComponentsDocsRouteRouteChildren = {
  ComponentsDocsSlugRoute: ComponentsDocsSlugRoute,
  ComponentsDocsAnimatedCounterRoute: ComponentsDocsAnimatedCounterRoute,
  ComponentsDocsBounceSidebarRoute: ComponentsDocsBounceSidebarRoute,
  ComponentsDocsCodeBlockRoute: ComponentsDocsCodeBlockRoute,
  ComponentsDocsDeleteButtonRoute: ComponentsDocsDeleteButtonRoute,
  ComponentsDocsDurationPickerRoute: ComponentsDocsDurationPickerRoute,
  ComponentsDocsEmojiReactionRoute: ComponentsDocsEmojiReactionRoute,
  ComponentsDocsFamilyDrawerRoute: ComponentsDocsFamilyDrawerRoute,
  ComponentsDocsFluidOrbRoute: ComponentsDocsFluidOrbRoute,
  ComponentsDocsFolderComponentRoute: ComponentsDocsFolderComponentRoute,
  ComponentsDocsGithubActivityRoute: ComponentsDocsGithubActivityRoute,
  ComponentsDocsGooeyNavRoute: ComponentsDocsGooeyNavRoute,
  ComponentsDocsGravityLettersRoute: ComponentsDocsGravityLettersRoute,
  ComponentsDocsGridRevealRoute: ComponentsDocsGridRevealRoute,
  ComponentsDocsHookSidebarRoute: ComponentsDocsHookSidebarRoute,
  ComponentsDocsMatrixOrbRoute: ComponentsDocsMatrixOrbRoute,
  ComponentsDocsNotificationBellRoute: ComponentsDocsNotificationBellRoute,
  ComponentsDocsOtpInputRoute: ComponentsDocsOtpInputRoute,
  ComponentsDocsProximitySidebarRoute: ComponentsDocsProximitySidebarRoute,
  ComponentsDocsScrollProgressRoute: ComponentsDocsScrollProgressRoute,
  ComponentsDocsStepPlayerRoute: ComponentsDocsStepPlayerRoute,
  ComponentsDocsTaskListRoute: ComponentsDocsTaskListRoute,
}

const ComponentsDocsRouteRouteWithChildren =
  ComponentsDocsRouteRoute._addFileChildren(ComponentsDocsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderComponentRoute: FolderComponentRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ComponentsDocsRouteRoute: ComponentsDocsRouteRouteWithChildren,
  ApiSourceRoute: ApiSourceRoute,
  SponsorsThankYouRoute: SponsorsThankYouRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
