/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FolderComponentRouteImport } from './routes/folder-component'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ApiSourceRouteImport } from './routes/api.source'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as ComponentsDocsRouteRouteImport } from './routes/components/_docs/route'
import { Route as SponsorsIndexRouteImport } from './routes/sponsors/index'
import { Route as SponsorsThankYouRouteImport } from './routes/sponsors/thank-you'
import { Route as ComponentsDocsSlugRouteImport } from './routes/components/_docs/$slug'
import { Route as ComponentsDocsAnimatedcounterRouteImport } from './routes/components/_docs/animatedcounter'
import { Route as ComponentsDocsBouncesidebarRouteImport } from './routes/components/_docs/bouncesidebar'
import { Route as ComponentsDocsCodeblockRouteImport } from './routes/components/_docs/codeblock'
import { Route as ComponentsDocsDeletebuttonRouteImport } from './routes/components/_docs/deletebutton'
import { Route as ComponentsDocsDurationpickerRouteImport } from './routes/components/_docs/durationpicker'
import { Route as ComponentsDocsEmojireactionRouteImport } from './routes/components/_docs/emojireaction'
import { Route as ComponentsDocsFamilydrawerRouteImport } from './routes/components/_docs/familydrawer'
import { Route as ComponentsDocsFluidorbRouteImport } from './routes/components/_docs/fluidorb'
import { Route as ComponentsDocsFoldercomponentRouteImport } from './routes/components/_docs/foldercomponent'
import { Route as ComponentsDocsGithubactivityRouteImport } from './routes/components/_docs/githubactivity'
import { Route as ComponentsDocsGooeynavRouteImport } from './routes/components/_docs/gooeynav'
import { Route as ComponentsDocsGravitylettersRouteImport } from './routes/components/_docs/gravityletters'
import { Route as ComponentsDocsGridrevealRouteImport } from './routes/components/_docs/gridreveal'
import { Route as ComponentsDocsHooksidebarRouteImport } from './routes/components/_docs/hooksidebar'
import { Route as ComponentsDocsMatrixorbRouteImport } from './routes/components/_docs/matrixorb'
import { Route as ComponentsDocsNotificationbellRouteImport } from './routes/components/_docs/notificationbell'
import { Route as ComponentsDocsOtpinputRouteImport } from './routes/components/_docs/otpinput'
import { Route as ComponentsDocsProximitysidebarRouteImport } from './routes/components/_docs/proximitysidebar'
import { Route as ComponentsDocsScrollprogressindicatorRouteImport } from './routes/components/_docs/scrollprogressindicator'
import { Route as ComponentsDocsStepplayerRouteImport } from './routes/components/_docs/stepplayer'
import { Route as ComponentsDocsTasklistRouteImport } from './routes/components/_docs/tasklist'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FolderComponentRoute = FolderComponentRouteImport.update({
  id: '/folder-component',
  path: '/folder-component',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourceRoute = ApiSourceRouteImport.update({
  id: '/api/source',
  path: '/api/source',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDocsRouteRoute = ComponentsDocsRouteRouteImport.update({
  id: '/components/_docs',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsIndexRoute = SponsorsIndexRouteImport.update({
  id: '/sponsors/',
  path: '/sponsors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsThankYouRoute = SponsorsThankYouRouteImport.update({
  id: '/sponsors/thank-you',
  path: '/sponsors/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsDocsSlugRoute = ComponentsDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsAnimatedcounterRoute =
  ComponentsDocsAnimatedcounterRouteImport.update({
    id: '/animatedcounter',
    path: '/animatedcounter',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsBouncesidebarRoute =
  ComponentsDocsBouncesidebarRouteImport.update({
    id: '/bouncesidebar',
    path: '/bouncesidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsCodeblockRoute = ComponentsDocsCodeblockRouteImport.update({
  id: '/codeblock',
  path: '/codeblock',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsDeletebuttonRoute =
  ComponentsDocsDeletebuttonRouteImport.update({
    id: '/deletebutton',
    path: '/deletebutton',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsDurationpickerRoute =
  ComponentsDocsDurationpickerRouteImport.update({
    id: '/durationpicker',
    path: '/durationpicker',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsEmojireactionRoute =
  ComponentsDocsEmojireactionRouteImport.update({
    id: '/emojireaction',
    path: '/emojireaction',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsFamilydrawerRoute =
  ComponentsDocsFamilydrawerRouteImport.update({
    id: '/familydrawer',
    path: '/familydrawer',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsFluidorbRoute = ComponentsDocsFluidorbRouteImport.update({
  id: '/fluidorb',
  path: '/fluidorb',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsFoldercomponentRoute =
  ComponentsDocsFoldercomponentRouteImport.update({
    id: '/foldercomponent',
    path: '/foldercomponent',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGithubactivityRoute =
  ComponentsDocsGithubactivityRouteImport.update({
    id: '/githubactivity',
    path: '/githubactivity',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGooeynavRoute = ComponentsDocsGooeynavRouteImport.update({
  id: '/gooeynav',
  path: '/gooeynav',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsGravitylettersRoute =
  ComponentsDocsGravitylettersRouteImport.update({
    id: '/gravityletters',
    path: '/gravityletters',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsGridrevealRoute =
  ComponentsDocsGridrevealRouteImport.update({
    id: '/gridreveal',
    path: '/gridreveal',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsHooksidebarRoute =
  ComponentsDocsHooksidebarRouteImport.update({
    id: '/hooksidebar',
    path: '/hooksidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsMatrixorbRoute = ComponentsDocsMatrixorbRouteImport.update({
  id: '/matrixorb',
  path: '/matrixorb',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsNotificationbellRoute =
  ComponentsDocsNotificationbellRouteImport.update({
    id: '/notificationbell',
    path: '/notificationbell',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsOtpinputRoute = ComponentsDocsOtpinputRouteImport.update({
  id: '/otpinput',
  path: '/otpinput',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)
const ComponentsDocsProximitysidebarRoute =
  ComponentsDocsProximitysidebarRouteImport.update({
    id: '/proximitysidebar',
    path: '/proximitysidebar',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsScrollprogressindicatorRoute =
  ComponentsDocsScrollprogressindicatorRouteImport.update({
    id: '/scrollprogressindicator',
    path: '/scrollprogressindicator',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsStepplayerRoute =
  ComponentsDocsStepplayerRouteImport.update({
    id: '/stepplayer',
    path: '/stepplayer',
    getParentRoute: () => ComponentsDocsRouteRoute,
  } as any)
const ComponentsDocsTasklistRoute = ComponentsDocsTasklistRouteImport.update({
  id: '/tasklist',
  path: '/tasklist',
  getParentRoute: () => ComponentsDocsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components': typeof ComponentsDocsRouteRouteWithChildren
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/components/': typeof ComponentsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/components/$slug': typeof ComponentsDocsSlugRoute
  '/components/animatedcounter': typeof ComponentsDocsAnimatedcounterRoute
  '/components/bouncesidebar': typeof ComponentsDocsBouncesidebarRoute
  '/components/codeblock': typeof ComponentsDocsCodeblockRoute
  '/components/deletebutton': typeof ComponentsDocsDeletebuttonRoute
  '/components/durationpicker': typeof ComponentsDocsDurationpickerRoute
  '/components/emojireaction': typeof ComponentsDocsEmojireactionRoute
  '/components/familydrawer': typeof ComponentsDocsFamilydrawerRoute
  '/components/fluidorb': typeof ComponentsDocsFluidorbRoute
  '/components/foldercomponent': typeof ComponentsDocsFoldercomponentRoute
  '/components/githubactivity': typeof ComponentsDocsGithubactivityRoute
  '/components/gooeynav': typeof ComponentsDocsGooeynavRoute
  '/components/gravityletters': typeof ComponentsDocsGravitylettersRoute
  '/components/gridreveal': typeof ComponentsDocsGridrevealRoute
  '/components/hooksidebar': typeof ComponentsDocsHooksidebarRoute
  '/components/matrixorb': typeof ComponentsDocsMatrixorbRoute
  '/components/notificationbell': typeof ComponentsDocsNotificationbellRoute
  '/components/otpinput': typeof ComponentsDocsOtpinputRoute
  '/components/proximitysidebar': typeof ComponentsDocsProximitysidebarRoute
  '/components/scrollprogressindicator': typeof ComponentsDocsScrollprogressindicatorRoute
  '/components/stepplayer': typeof ComponentsDocsStepplayerRoute
  '/components/tasklist': typeof ComponentsDocsTasklistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components': typeof ComponentsIndexRoute
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/sponsors': typeof SponsorsIndexRoute
  '/components/$slug': typeof ComponentsDocsSlugRoute
  '/components/animatedcounter': typeof ComponentsDocsAnimatedcounterRoute
  '/components/bouncesidebar': typeof ComponentsDocsBouncesidebarRoute
  '/components/codeblock': typeof ComponentsDocsCodeblockRoute
  '/components/deletebutton': typeof ComponentsDocsDeletebuttonRoute
  '/components/durationpicker': typeof ComponentsDocsDurationpickerRoute
  '/components/emojireaction': typeof ComponentsDocsEmojireactionRoute
  '/components/familydrawer': typeof ComponentsDocsFamilydrawerRoute
  '/components/fluidorb': typeof ComponentsDocsFluidorbRoute
  '/components/foldercomponent': typeof ComponentsDocsFoldercomponentRoute
  '/components/githubactivity': typeof ComponentsDocsGithubactivityRoute
  '/components/gooeynav': typeof ComponentsDocsGooeynavRoute
  '/components/gravityletters': typeof ComponentsDocsGravitylettersRoute
  '/components/gridreveal': typeof ComponentsDocsGridrevealRoute
  '/components/hooksidebar': typeof ComponentsDocsHooksidebarRoute
  '/components/matrixorb': typeof ComponentsDocsMatrixorbRoute
  '/components/notificationbell': typeof ComponentsDocsNotificationbellRoute
  '/components/otpinput': typeof ComponentsDocsOtpinputRoute
  '/components/proximitysidebar': typeof ComponentsDocsProximitysidebarRoute
  '/components/scrollprogressindicator': typeof ComponentsDocsScrollprogressindicatorRoute
  '/components/stepplayer': typeof ComponentsDocsStepplayerRoute
  '/components/tasklist': typeof ComponentsDocsTasklistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/folder-component': typeof FolderComponentRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/components/_docs': typeof ComponentsDocsRouteRouteWithChildren
  '/api/source': typeof ApiSourceRoute
  '/sponsors/thank-you': typeof SponsorsThankYouRoute
  '/components/': typeof ComponentsIndexRoute
  '/sponsors/': typeof SponsorsIndexRoute
  '/components/_docs/$slug': typeof ComponentsDocsSlugRoute
  '/components/_docs/animatedcounter': typeof ComponentsDocsAnimatedcounterRoute
  '/components/_docs/bouncesidebar': typeof ComponentsDocsBouncesidebarRoute
  '/components/_docs/codeblock': typeof ComponentsDocsCodeblockRoute
  '/components/_docs/deletebutton': typeof ComponentsDocsDeletebuttonRoute
  '/components/_docs/durationpicker': typeof ComponentsDocsDurationpickerRoute
  '/components/_docs/emojireaction': typeof ComponentsDocsEmojireactionRoute
  '/components/_docs/familydrawer': typeof ComponentsDocsFamilydrawerRoute
  '/components/_docs/fluidorb': typeof ComponentsDocsFluidorbRoute
  '/components/_docs/foldercomponent': typeof ComponentsDocsFoldercomponentRoute
  '/components/_docs/githubactivity': typeof ComponentsDocsGithubactivityRoute
  '/components/_docs/gooeynav': typeof ComponentsDocsGooeynavRoute
  '/components/_docs/gravityletters': typeof ComponentsDocsGravitylettersRoute
  '/components/_docs/gridreveal': typeof ComponentsDocsGridrevealRoute
  '/components/_docs/hooksidebar': typeof ComponentsDocsHooksidebarRoute
  '/components/_docs/matrixorb': typeof ComponentsDocsMatrixorbRoute
  '/components/_docs/notificationbell': typeof ComponentsDocsNotificationbellRoute
  '/components/_docs/otpinput': typeof ComponentsDocsOtpinputRoute
  '/components/_docs/proximitysidebar': typeof ComponentsDocsProximitysidebarRoute
  '/components/_docs/scrollprogressindicator': typeof ComponentsDocsScrollprogressindicatorRoute
  '/components/_docs/stepplayer': typeof ComponentsDocsStepplayerRoute
  '/components/_docs/tasklist': typeof ComponentsDocsTasklistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/components/'
    | '/sponsors/'
    | '/components/$slug'
    | '/components/animatedcounter'
    | '/components/bouncesidebar'
    | '/components/codeblock'
    | '/components/deletebutton'
    | '/components/durationpicker'
    | '/components/emojireaction'
    | '/components/familydrawer'
    | '/components/fluidorb'
    | '/components/foldercomponent'
    | '/components/githubactivity'
    | '/components/gooeynav'
    | '/components/gravityletters'
    | '/components/gridreveal'
    | '/components/hooksidebar'
    | '/components/matrixorb'
    | '/components/notificationbell'
    | '/components/otpinput'
    | '/components/proximitysidebar'
    | '/components/scrollprogressindicator'
    | '/components/stepplayer'
    | '/components/tasklist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/sponsors'
    | '/components/$slug'
    | '/components/animatedcounter'
    | '/components/bouncesidebar'
    | '/components/codeblock'
    | '/components/deletebutton'
    | '/components/durationpicker'
    | '/components/emojireaction'
    | '/components/familydrawer'
    | '/components/fluidorb'
    | '/components/foldercomponent'
    | '/components/githubactivity'
    | '/components/gooeynav'
    | '/components/gravityletters'
    | '/components/gridreveal'
    | '/components/hooksidebar'
    | '/components/matrixorb'
    | '/components/notificationbell'
    | '/components/otpinput'
    | '/components/proximitysidebar'
    | '/components/scrollprogressindicator'
    | '/components/stepplayer'
    | '/components/tasklist'
  id:
    | '__root__'
    | '/'
    | '/folder-component'
    | '/llms.txt'
    | '/privacy'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/terms'
    | '/testimonials'
    | '/components/_docs'
    | '/api/source'
    | '/sponsors/thank-you'
    | '/components/'
    | '/sponsors/'
    | '/components/_docs/$slug'
    | '/components/_docs/animatedcounter'
    | '/components/_docs/bouncesidebar'
    | '/components/_docs/codeblock'
    | '/components/_docs/deletebutton'
    | '/components/_docs/durationpicker'
    | '/components/_docs/emojireaction'
    | '/components/_docs/familydrawer'
    | '/components/_docs/fluidorb'
    | '/components/_docs/foldercomponent'
    | '/components/_docs/githubactivity'
    | '/components/_docs/gooeynav'
    | '/components/_docs/gravityletters'
    | '/components/_docs/gridreveal'
    | '/components/_docs/hooksidebar'
    | '/components/_docs/matrixorb'
    | '/components/_docs/notificationbell'
    | '/components/_docs/otpinput'
    | '/components/_docs/proximitysidebar'
    | '/components/_docs/scrollprogressindicator'
    | '/components/_docs/stepplayer'
    | '/components/_docs/tasklist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FolderComponentRoute: typeof FolderComponentRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ComponentsDocsRouteRoute: typeof ComponentsDocsRouteRouteWithChildren
  ApiSourceRoute: typeof ApiSourceRoute
  SponsorsThankYouRoute: typeof SponsorsThankYouRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
  SponsorsIndexRoute: typeof SponsorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folder-component': {
      id: '/folder-component'
      path: '/folder-component'
      fullPath: '/folder-component'
      preLoaderRoute: typeof FolderComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/source': {
      id: '/api/source'
      path: '/api/source'
      fullPath: '/api/source'
      preLoaderRoute: typeof ApiSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/_docs': {
      id: '/components/_docs'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsDocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/': {
      id: '/sponsors/'
      path: '/sponsors'
      fullPath: '/sponsors/'
      preLoaderRoute: typeof SponsorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors/thank-you': {
      id: '/sponsors/thank-you'
      path: '/sponsors/thank-you'
      fullPath: '/sponsors/thank-you'
      preLoaderRoute: typeof SponsorsThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/_docs/$slug': {
      id: '/components/_docs/$slug'
      path: '/$slug'
      fullPath: '/components/$slug'
      preLoaderRoute: typeof ComponentsDocsSlugRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/animatedcounter': {
      id: '/components/_docs/animatedcounter'
      path: '/animatedcounter'
      fullPath: '/components/animatedcounter'
      preLoaderRoute: typeof ComponentsDocsAnimatedcounterRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/bouncesidebar': {
      id: '/components/_docs/bouncesidebar'
      path: '/bouncesidebar'
      fullPath: '/components/bouncesidebar'
      preLoaderRoute: typeof ComponentsDocsBouncesidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/codeblock': {
      id: '/components/_docs/codeblock'
      path: '/codeblock'
      fullPath: '/components/codeblock'
      preLoaderRoute: typeof ComponentsDocsCodeblockRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/deletebutton': {
      id: '/components/_docs/deletebutton'
      path: '/deletebutton'
      fullPath: '/components/deletebutton'
      preLoaderRoute: typeof ComponentsDocsDeletebuttonRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/durationpicker': {
      id: '/components/_docs/durationpicker'
      path: '/durationpicker'
      fullPath: '/components/durationpicker'
      preLoaderRoute: typeof ComponentsDocsDurationpickerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/emojireaction': {
      id: '/components/_docs/emojireaction'
      path: '/emojireaction'
      fullPath: '/components/emojireaction'
      preLoaderRoute: typeof ComponentsDocsEmojireactionRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/familydrawer': {
      id: '/components/_docs/familydrawer'
      path: '/familydrawer'
      fullPath: '/components/familydrawer'
      preLoaderRoute: typeof ComponentsDocsFamilydrawerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/fluidorb': {
      id: '/components/_docs/fluidorb'
      path: '/fluidorb'
      fullPath: '/components/fluidorb'
      preLoaderRoute: typeof ComponentsDocsFluidorbRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/foldercomponent': {
      id: '/components/_docs/foldercomponent'
      path: '/foldercomponent'
      fullPath: '/components/foldercomponent'
      preLoaderRoute: typeof ComponentsDocsFoldercomponentRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/githubactivity': {
      id: '/components/_docs/githubactivity'
      path: '/githubactivity'
      fullPath: '/components/githubactivity'
      preLoaderRoute: typeof ComponentsDocsGithubactivityRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/gooeynav': {
      id: '/components/_docs/gooeynav'
      path: '/gooeynav'
      fullPath: '/components/gooeynav'
      preLoaderRoute: typeof ComponentsDocsGooeynavRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/gravityletters': {
      id: '/components/_docs/gravityletters'
      path: '/gravityletters'
      fullPath: '/components/gravityletters'
      preLoaderRoute: typeof ComponentsDocsGravitylettersRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/gridreveal': {
      id: '/components/_docs/gridreveal'
      path: '/gridreveal'
      fullPath: '/components/gridreveal'
      preLoaderRoute: typeof ComponentsDocsGridrevealRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/hooksidebar': {
      id: '/components/_docs/hooksidebar'
      path: '/hooksidebar'
      fullPath: '/components/hooksidebar'
      preLoaderRoute: typeof ComponentsDocsHooksidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/matrixorb': {
      id: '/components/_docs/matrixorb'
      path: '/matrixorb'
      fullPath: '/components/matrixorb'
      preLoaderRoute: typeof ComponentsDocsMatrixorbRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/notificationbell': {
      id: '/components/_docs/notificationbell'
      path: '/notificationbell'
      fullPath: '/components/notificationbell'
      preLoaderRoute: typeof ComponentsDocsNotificationbellRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/otpinput': {
      id: '/components/_docs/otpinput'
      path: '/otpinput'
      fullPath: '/components/otpinput'
      preLoaderRoute: typeof ComponentsDocsOtpinputRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/proximitysidebar': {
      id: '/components/_docs/proximitysidebar'
      path: '/proximitysidebar'
      fullPath: '/components/proximitysidebar'
      preLoaderRoute: typeof ComponentsDocsProximitysidebarRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/scrollprogressindicator': {
      id: '/components/_docs/scrollprogressindicator'
      path: '/scrollprogressindicator'
      fullPath: '/components/scrollprogressindicator'
      preLoaderRoute: typeof ComponentsDocsScrollprogressindicatorRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/stepplayer': {
      id: '/components/_docs/stepplayer'
      path: '/stepplayer'
      fullPath: '/components/stepplayer'
      preLoaderRoute: typeof ComponentsDocsStepplayerRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
    '/components/_docs/tasklist': {
      id: '/components/_docs/tasklist'
      path: '/tasklist'
      fullPath: '/components/tasklist'
      preLoaderRoute: typeof ComponentsDocsTasklistRouteImport
      parentRoute: typeof ComponentsDocsRouteRoute
    }
  }
}

interface ComponentsDocsRouteRouteChildren {
  ComponentsDocsSlugRoute: typeof ComponentsDocsSlugRoute
  ComponentsDocsAnimatedcounterRoute: typeof ComponentsDocsAnimatedcounterRoute
  ComponentsDocsBouncesidebarRoute: typeof ComponentsDocsBouncesidebarRoute
  ComponentsDocsCodeblockRoute: typeof ComponentsDocsCodeblockRoute
  ComponentsDocsDeletebuttonRoute: typeof ComponentsDocsDeletebuttonRoute
  ComponentsDocsDurationpickerRoute: typeof ComponentsDocsDurationpickerRoute
  ComponentsDocsEmojireactionRoute: typeof ComponentsDocsEmojireactionRoute
  ComponentsDocsFamilydrawerRoute: typeof ComponentsDocsFamilydrawerRoute
  ComponentsDocsFluidorbRoute: typeof ComponentsDocsFluidorbRoute
  ComponentsDocsFoldercomponentRoute: typeof ComponentsDocsFoldercomponentRoute
  ComponentsDocsGithubactivityRoute: typeof ComponentsDocsGithubactivityRoute
  ComponentsDocsGooeynavRoute: typeof ComponentsDocsGooeynavRoute
  ComponentsDocsGravitylettersRoute: typeof ComponentsDocsGravitylettersRoute
  ComponentsDocsGridrevealRoute: typeof ComponentsDocsGridrevealRoute
  ComponentsDocsHooksidebarRoute: typeof ComponentsDocsHooksidebarRoute
  ComponentsDocsMatrixorbRoute: typeof ComponentsDocsMatrixorbRoute
  ComponentsDocsNotificationbellRoute: typeof ComponentsDocsNotificationbellRoute
  ComponentsDocsOtpinputRoute: typeof ComponentsDocsOtpinputRoute
  ComponentsDocsProximitysidebarRoute: typeof ComponentsDocsProximitysidebarRoute
  ComponentsDocsScrollprogressindicatorRoute: typeof ComponentsDocsScrollprogressindicatorRoute
  ComponentsDocsStepplayerRoute: typeof ComponentsDocsStepplayerRoute
  ComponentsDocsTasklistRoute: typeof ComponentsDocsTasklistRoute
}

const ComponentsDocsRouteRouteChildren: ComponentsDocsRouteRouteChildren = {
  ComponentsDocsSlugRoute: ComponentsDocsSlugRoute,
  ComponentsDocsAnimatedcounterRoute: ComponentsDocsAnimatedcounterRoute,
  ComponentsDocsBouncesidebarRoute: ComponentsDocsBouncesidebarRoute,
  ComponentsDocsCodeblockRoute: ComponentsDocsCodeblockRoute,
  ComponentsDocsDeletebuttonRoute: ComponentsDocsDeletebuttonRoute,
  ComponentsDocsDurationpickerRoute: ComponentsDocsDurationpickerRoute,
  ComponentsDocsEmojireactionRoute: ComponentsDocsEmojireactionRoute,
  ComponentsDocsFamilydrawerRoute: ComponentsDocsFamilydrawerRoute,
  ComponentsDocsFluidorbRoute: ComponentsDocsFluidorbRoute,
  ComponentsDocsFoldercomponentRoute: ComponentsDocsFoldercomponentRoute,
  ComponentsDocsGithubactivityRoute: ComponentsDocsGithubactivityRoute,
  ComponentsDocsGooeynavRoute: ComponentsDocsGooeynavRoute,
  ComponentsDocsGravitylettersRoute: ComponentsDocsGravitylettersRoute,
  ComponentsDocsGridrevealRoute: ComponentsDocsGridrevealRoute,
  ComponentsDocsHooksidebarRoute: ComponentsDocsHooksidebarRoute,
  ComponentsDocsMatrixorbRoute: ComponentsDocsMatrixorbRoute,
  ComponentsDocsNotificationbellRoute: ComponentsDocsNotificationbellRoute,
  ComponentsDocsOtpinputRoute: ComponentsDocsOtpinputRoute,
  ComponentsDocsProximitysidebarRoute: ComponentsDocsProximitysidebarRoute,
  ComponentsDocsScrollprogressindicatorRoute:
    ComponentsDocsScrollprogressindicatorRoute,
  ComponentsDocsStepplayerRoute: ComponentsDocsStepplayerRoute,
  ComponentsDocsTasklistRoute: ComponentsDocsTasklistRoute,
}

const ComponentsDocsRouteRouteWithChildren =
  ComponentsDocsRouteRoute._addFileChildren(ComponentsDocsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FolderComponentRoute: FolderComponentRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ComponentsDocsRouteRoute: ComponentsDocsRouteRouteWithChildren,
  ApiSourceRoute: ApiSourceRoute,
  SponsorsThankYouRoute: SponsorsThankYouRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
  SponsorsIndexRoute: SponsorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
